name: instagram_stories_demo
description: A new Flutter project.

publish_to:


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #Cube Transition
  cube_transition_plus: ^2.0.1

  #State
  provider: ^6.0.5
  flutter_bloc: ^8.1.2

  #Firebase
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0

  #Video Player
  video_player: ^2.8.1

  #Responsive UI
  responsive_sizer: ^3.2.0

  #Material
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

