// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs0Xw1gI-gEv7vdn6b5wf0oO7Dz_72T0I',
    appId: '1:162214450817:web:507c029e19831f4b03df80',
    messagingSenderId: '162214450817',
    projectId: 'instagram-stories-3189f',
    authDomain: 'instagram-stories-3189f.firebaseapp.com',
    storageBucket: 'instagram-stories-3189f.appspot.com',
    measurementId: 'G-6Y2PXZTFXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk6dR7gRsddDwhdPzUC6WiYQYvxpTNX_E',
    appId: '1:162214450817:android:13d1c580d48d0eb603df80',
    messagingSenderId: '162214450817',
    projectId: 'instagram-stories-3189f',
    storageBucket: 'instagram-stories-3189f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBokZAWGFM8cWg8kJMiFaEmnk0iZo03VQc',
    appId: '1:162214450817:ios:331d5602861f1de703df80',
    messagingSenderId: '162214450817',
    projectId: 'instagram-stories-3189f',
    storageBucket: 'instagram-stories-3189f.appspot.com',
    iosBundleId: 'com.efertunc.instagramStoriesDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBokZAWGFM8cWg8kJMiFaEmnk0iZo03VQc',
    appId: '1:162214450817:ios:e649994b43ee85b003df80',
    messagingSenderId: '162214450817',
    projectId: 'instagram-stories-3189f',
    storageBucket: 'instagram-stories-3189f.appspot.com',
    iosBundleId: 'com.efertunc.instagramStoriesDemo.RunnerTests',
  );
}
